spring.application.name=Employee_Management_System_3

spring.datasource.url=jdbc:mysql://localhost:3306/employeemanagementsystem
spring.datasource.username=root
spring.datasource.password=0804
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=9638

server.servlet.context-path=/Employee_Management_System_3-3.2.2
